project_name: agregore_ipfs_daemon

before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
    overrides:
      - goos: linux
        goarch: arm
        goarm: ""
        gomips: ""
        tags:
          - androiddnsfix
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
archives:
  - format: binary
