name: "Build AAR with docker"

on:
  push:
    paths-ignore:
      - "**.md"
      - "LICENSE*"
    branches:
      - "main"
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: mkdir -p ~/image-cache
      - name: Get digest
        id: get-digest
        run: |
          echo "::set-output name=digest::$(docker manifest inspect makeworld/gomobile-android:latest -v | jq -r '.Descriptor.digest' | cut -d: -f2)"
        shell: bash

      - name: Load image cache
        id: image-cache
        uses: actions/cache@v3
        with:
          path: ~/image-cache
          key: image-cache-${{ steps.get-digest.outputs.digest }}

      - name: Download image if cache is outdated
        if: steps.image-cache.outputs.cache-hit != 'true'
        run: |
          docker pull makeworld/gomobile-android:latest
          docker save -o ~/image-cache/gomobile-android.tar makeworld/gomobile-android

      - name: Use cache if current
        if: steps.image-cache.outputs.cache-hit == 'true'
        run: docker load -i ~/image-cache/gomobile-android.tar

      - name: Commit or tag?
        id: commit-tag
        run: |
          if [[ ${{ startsWith(github.ref, 'refs/tags/') }} == 'true' ]]; then
              echo "::set-output name=ver::"
          else
              echo "::set-output name=ver::_${GITHUB_SHA}"
          fi

      - name: docker run
        run: |
          docker run -v ${GITHUB_WORKSPACE}:/module makeworld/gomobile-android \
          bind -target=android/arm -javapkg=moe.mauve.agregore.ipfs \
          -o agregore-ipfs-daemon${{ steps.commit-tag.outputs.ver }}.aar \
          ./gateway

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-

      - name: Desktop builds
        uses: actions/setup-go@v3
        with:
          go-version: "1.17.8"
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64   go build -o agregore-ipfs-daemon_linux_amd64${{ steps.commit-tag.outputs.ver }}
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o agregore-ipfs-daemon_windows_amd64${{ steps.commit-tag.outputs.ver }}.exe
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64  go build -o agregore-ipfs-daemon_macos_amd64${{ steps.commit-tag.outputs.ver }}

      - name: Upload artifact
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: actions/upload-artifact@v3
        with:
          name: AAR
          path: |
            agregore-ipfs-daemon*.aar
            agregore-ipfs-daemon_*
          if-no-files-found: error

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            agregore-ipfs-daemon*.aar
            agregore-ipfs-daemon_*
